security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto
            
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }

        my_provider:
            memory:
                users:
                    kumnito: { password: '$argon2id$v=19$m=65536,t=4,p=1$LjNtUlBid2hITkRCcWFEMw$1kKK5ZQPu9sn4L1teomJZSQT/vZpLgp5rwDE+OMHggg', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: my_provider

            form_login:
                login_path: connexion
                check_path: connexion
                default_target_path: accueil
            logout: 
                path:   app_logout

            guard:
                authenticators:
                    - App\Security\LoginAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/Administration, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
